### PR TITLE
#151. Fix users tab UI.

### PR DESCRIPTION
**Pull request by MatyashDen**

### CODE REVIEW

**Comment by MatyashDen** [comment]
@yevhenii-kanivets 
layout_weight = 1 doesn't fix the bug

**Comment by MatyashDen** [comment]
layout_weight >= 50 fixes

**Comment by yevhenii-kanivets** [comment]
Hm, I've checked it on my side, it worked :) but you can leave it as it is then.

**Comment by MatyashDen** [comment]
I checked in AS editor

**Pull request merged**
