### PR TITLE
Added Hindi translations for strings file

### PR DESCRIPTION
**Pull request by nishitkshah**

### CODE REVIEW

**Comment by yevhenii-kanivets** [comment]
@bogdan-evtushenko once you have free time, could you check that this translation works well with our layouts?

**Comment by nishitkshah** [comment]
"छांटे" would be more like "seperating things" instead of "order by". "क्रमबद्ध करें" would be more precise but I believe "सॉर्ट करें" would be simpler.

**Comment by Brijesh1in** [comment]
> "छांटे" would be more like "seperating things" instead of "order by". "क्रमबद्ध करें" would be more precise but I believe "सॉर्ट करें" would be simpler.

Yeah! you are right ."क्रमबद्ध करें" is better .

**Comment by yevhenii-kanivets** [comment]
@nishitkshah could you, please, make changes suggested by @Brijesh1in if you think they make sense, and also rename (and move) the file to `app/src/main/res/values-hi/strings.xml` (in such a way it will be used by application without any changes from our side)?

**Comment by yevhenii-kanivets** [comment]
Results for Google Form:

Capture d’écran 2019-11-25 à 15 50 55

Capture d’écran 2019-11-25 à 15 51 06

**Comment by nishitkshah** [comment]
Are you recommending that the Hindi Translation be skipped?

**Comment by yevhenii-kanivets** [comment]
@nishitkshah no, it was just for informational purpose 😄I will be happy to add Hindi translation even if there is only 5-10% of users, which will benefit from it.

**Comment by nishitkshah** [comment]
@yevhenii-kanivets made the changes

**Comment by nishitkshah** [comment]
@Brijesh1in I'm not incorporating the changes you recommended as I feel that problems and sort are pretty common words and their literal translation would keep the UI more intuitive.

**Pull request merged**
