### PR TITLE
204 update apps to display only blog posts with the latest comment

### PR DESCRIPTION
**Pull request by MatyashDen**

### CODE REVIEW

**Comment by MatyashDen** [comment]
@bogdan-evtushenko @karavaiev-gh 
To test it you need to run backend local server, ping me how to do it

**Review by yevhenii-kanivets — CHANGES_REQUESTED** [review]
Very good job 👍 

I find it more engaging and meaningful. Functionally, let's make the only change, if possible: open the pre-scrolled Codeforces post when clicked on the comment.

There are a few nitpicks / questions about code style.

**Comment by yevhenii-kanivets** [comment]
@bogdan-evtushenko @karavaiev-gh I've made the code review, so you only need to make a functional review, which is quite simple:
1. Checkout this PR.
2. Change `API_LINK = "algoris-me-backend.herokuapp.com" to "algoris-me-backend-staging.herokuapp.com"`.
3. Run Android app, and check if new feed looks OK to you.
4. Run iOS app, and do the same.

It won't take more then 30 minutes, so, please, do it in priority on Monday.

**Comment by karavaiev-gh** [comment]
image
about the label "Click to see" | IOS

**Comment by karavaiev-gh** [comment]
And if I click on the cross (info field), I will switch to info post. It's correct?

**Comment by MatyashDen** [comment]
> And if I click on the cross (info field), I will switch to info post. It's correct? | IOS

Try not to test on IOS 14)

**Review by yevhenii-kanivets — APPROVED** [review]
@MatyashDen perfect now 👍 After a quick check, it seems like the problem isn't related to UI rendering, and actually isn't that big on other devices (my Pixel 3a and 2 simulators I have).

I think, that actual problem is related to parsing JSON on UI thread, which shouldn't happen in theory. Fixing of this issue requires the change of coroutines solution. I'll create the issue for the next milestone.

**Pull request merged**
